### ISSUE TITLE
Đ (U+0110) character is not rendered properly

### ISSUE THREAD

**Issue by jernejs** [madmalik/mononoki#89]
The Đ character (LATIN CAPITAL LETTER D WITH STROKE, U+0110) in Mononoki is rendered as D̅, when it should look the same as U+00D0 (Ð, LATIN CAPITAL LETTER ETH).

Example:
![Image1](https://user-images.githubusercontent.com/1800143/157058464-4ab1d66f-7f52-4eb9-ad58-874ea2007291.png)

**Comment by madmalik** [comment]
fixed! Thanks for the catch

**Comment by dscorbett** [comment]
This bug returned in version 1.5 and is still present in 1.6.

**Comment by madmalik** [comment]
Thanks for reporting! I fixed the issue and it will be included in the next release.
